"""What alembic needs to know about a site, and nothing more.

Migrations are the one place where a plugin system has to reach outside the
running application. Autogenerate compares the database against
`db.metadata`, and a model only reaches that metadata when its module is
imported -- so an app whose models nothing has imported is invisible, and its
tables silently never get created.

Importing every installed app's models is therefore all that alembic needs from
podpack. Note what it deliberately does *not* need: a Flask app, a secret key,
or a working database URI at import time. Keeping the migration environment out
of the application factory means a broken factory is not also a broken
migration.
"""

import pathlib
from typing import Any

from sqlalchemy import MetaData

from .config import installed_apps, load_host_config
from .registry import import_app_models


def target_metadata(config_path: str | pathlib.Path | None = None) -> MetaData:
    """The metadata alembic should compare the database against.

    Read this as the honest statement of the footgun it implies: the result
    describes exactly the apps this site currently has enabled. Run autogenerate
    with an app removed from the config file and alembic will faithfully propose
    dropping that app's tables, because from where it is standing they are
    tables no app claims. Django answers this with per-app migration
    directories; podpack has one history, so the answer for now is to autogenerate
    against the full app list.
    """
    from . import db

    host_config = load_host_config(config_path)
    import_app_models(installed_apps(host_config))
    return db.metadata


AUTHORING_DIALECT = "postgresql"
"""The only engine a revision may be authored against.

Every podpack site deploys on PostgreSQL (ADR-0029), including the one that
points at a managed instance rather than running a container -- so there is
no legitimate exception, and therefore no flag to escape through.
"""


def refuse_foreign_autogenerate(context: Any, revision: Any, directives: Any) -> None:
    """Stop `alembic revision --autogenerate` on the wrong engine.

    An alembic `process_revision_directives` hook, so it fires for
    autogenerate alone: `upgrade`, `downgrade` and a hand-written `revision`
    are untouched.

    The hazard is measured rather than theoretical, and this project has it
    in its own history. From the same models on the same day, SQLite
    autogenerated `server_default=sa.text('(CURRENT_TIMESTAMP)')` where
    PostgreSQL wants `now()`; and a revision that alters a column cannot even
    be applied to SQLite, because `ALTER TABLE ... ALTER COLUMN` is not its
    syntax -- holdenweb.com's baseline had to grow an inspection guard for
    exactly that.

    Refused rather than warned. A warning scrolls past in a wall of alembic
    logging; what survives is a file that outlives the laptop and is applied
    to production by a container nobody is watching.
    """
    if context.dialect.name == AUTHORING_DIALECT:
        return
    if not directives or directives[0].upgrade_ops.is_empty():
        return          # nothing detected, so nothing to get wrong
    raise RuntimeError(
        f"refusing to autogenerate against {context.dialect.name}: this site "
        f"deploys on {AUTHORING_DIALECT}, and a revision written here can be "
        f"one PostgreSQL rejects. Point SQLALCHEMY_DATABASE_URI at a "
        f"PostgreSQL first -- `dev.env` names your local one. Applying "
        f"migrations (`alembic upgrade head`) is not restricted."
    )
